version: "3.8"

services:
  frontend:
    build: ./frontend/create-react-app
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DOCUMENTDB_URI: mongodb://mongo:27017/URLShortener
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
