version: "3.8"
services:
  frontend:
    build: ./frontend/create-react-app
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
