# .github/workflows/startup.yml
name: Startup Workflow
on:
  workflow_dispatch:

jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infrastructure

      - name: Apply Terraform Configuration for Scaling Up ECS and ASG
        run: |
          terraform apply -auto-approve \
            -var 'ecs_desired_count=1' \
            -var 'asg_min_size=1' \
            -var 'asg_max_size=3' \
            -var 'asg_desired_capacity=1'
        working-directory: ./infrastructure
